In [1]:
import numpy as np

## 1D array

In [2]:
a = np.array([10, 2, 4, 50])
a

array([10,  2,  4, 50])

In [3]:
np.pad(a, pad_width=1, mode='wrap')

array([50, 10,  2,  4, 50, 10])

## 2D array

In [4]:
a = np.array([[10, 2, 4, 50], [5, 4, 1, -3]])
a

array([[10,  2,  4, 50],
       [ 5,  4,  1, -3]])

In [5]:
np.pad(a, pad_width=1, mode='wrap')

array([[-3,  5,  4,  1, -3,  5],
       [50, 10,  2,  4, 50, 10],
       [-3,  5,  4,  1, -3,  5],
       [50, 10,  2,  4, 50, 10]])

## vector field

In [6]:
a = np.ones((3, 2, 2, 3))

import discretisedfield as df

padding_sequence = df.util.assemble_index((0, 0), 4, {0: (1, 1)})
padding_sequence

((1, 1), (0, 0), (0, 0), (0, 0))

In [7]:
np.pad(a, pad_width=((1, 1), (0, 0), (0, 0), (0, 0)), mode='constant')

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [8]:
a

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [9]:
np.delete(a, (0, -1), axis=0)

<ipython-input-9-c5e3a0657cac>:1: FutureWarning: in the future negative indices will not be ignored by `numpy.delete`.
  np.delete(a, (0, -1), axis=0)


array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [10]:
a = np.array([[10, 2, 4, 50], [5, 4, 1, -3]])
a

array([[10,  2,  4, 50],
       [ 5,  4,  1, -3]])

In [11]:
np.delete(a, (0, a.shape[1]-1), axis=1)

array([[2, 4],
       [4, 1]])

In [12]:
a = np.array([1, 2, 3, 4])
np.gradient(a)

array([1., 1., 1., 1.])

In [15]:
pa = np.pad(a, (1, 1))
pa

array([0, 1, 2, 3, 4, 0])

In [16]:
np.gradient(pa)

array([ 1. ,  1. ,  1. ,  1. , -1.5, -4. ])

In [18]:
a = np.ones((2, 1, 1, 3))
a

array([[[[1., 1., 1.]]],


       [[[1., 1., 1.]]]])

In [20]:
np.pad(a, ((1, 1), (0, 0), (0, 0), (0, 0))).shape

(4, 1, 1, 3)